Algoritmo "Soma"

Problema "soma"
Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes
números. 

Var

x,y,soma : real


Inicio

escreval("Olá, neste programa você fará a somatoria dos números!")

escreva("Digite um número: ")
leia(x)

escreva("Digite outro número: ")
leia(y)

soma <- x+y

escreva("A soma de ",x," e ",y," é o número: " ,soma)

Fimalgoritmo
